import { InventoryItem, InventoryTransaction, Customer, Employee, Job, FinancialTransaction, DailyWorkLog } from './types';

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-01',
    name: 'American Walnut (2" x 12")',
    category: 'Lumber',
    unit: 'Board Feet',
    currentStock: 850,
    minStockThreshold: 150,
    unitCost: 16.5,
    lastUpdated: '2026-07-18',
  },
  {
    id: 'inv-02',
    name: 'White Oak Planks (1.5" x 8")',
    category: 'Lumber',
    unit: 'Board Feet',
    currentStock: 620,
    minStockThreshold: 100,
    unitCost: 14.8,
    lastUpdated: '2026-07-19',
  },
  {
    id: 'inv-03',
    name: 'Hard Maple Board (1" x 6")',
    category: 'Lumber',
    unit: 'Board Feet',
    currentStock: 450,
    minStockThreshold: 80,
    unitCost: 13.5,
    lastUpdated: '2026-07-15',
  },
  {
    id: 'inv-04',
    name: 'Premium Teak Planks',
    category: 'Lumber',
    unit: 'Board Feet',
    currentStock: 320,
    minStockThreshold: 80,
    unitCost: 18.0,
    lastUpdated: '2026-07-18',
  },
  {
    id: 'inv-05',
    name: 'Reclaimed Pine Wood',
    category: 'Lumber',
    unit: 'Board Feet',
    currentStock: 550,
    minStockThreshold: 120,
    unitCost: 9.5,
    lastUpdated: '2026-07-10',
  },
  {
    id: 'inv-06',
    name: 'Gorilla Wood Glue Premium',
    category: 'Adhesives',
    unit: 'Liters',
    currentStock: 18,
    minStockThreshold: 5,
    unitCost: 22.0,
    lastUpdated: '2026-07-19',
  },
  {
    id: 'inv-07',
    name: 'High-Gloss Polyurethane Lacquer',
    category: 'Finishes',
    unit: 'Liters',
    currentStock: 25,
    minStockThreshold: 8,
    unitCost: 28.5,
    lastUpdated: '2026-07-19',
  },
  {
    id: 'inv-08',
    name: 'Solid Brass Drawer Pulls (96mm)',
    category: 'Hardware',
    unit: 'Pieces',
    currentStock: 120,
    minStockThreshold: 30,
    unitCost: 8.5,
    lastUpdated: '2026-07-14',
  },
  {
    id: 'inv-09',
    name: 'Heavy-Duty Ball Bearing Drawer Slides',
    category: 'Hardware',
    unit: 'Pieces',
    currentStock: 8, // LOW STOCK TRIGGER!
    minStockThreshold: 20,
    unitCost: 15.0,
    lastUpdated: '2026-07-12',
  },
  {
    id: 'inv-10',
    name: 'Premium Wood Screws Box (Assorted)',
    category: 'Hardware',
    unit: 'Boxes',
    currentStock: 15,
    minStockThreshold: 5,
    unitCost: 35.0,
    lastUpdated: '2026-07-16',
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-01',
    name: 'Aminata Kallon',
    company: 'Elite Residences Ltd',
    phone: '+232 76 455 6789',
    email: 'aminata.kallon@eliteresidences.com',
    address: 'Plot 42, Wilkinson Road, Freetown',
    notes: 'High-end developer. Demands impeccable finishing and flawless grain alignment.',
    registrationDate: '2026-05-10',
  },
  {
    id: 'cust-02',
    name: 'Joseph Saidu',
    company: 'Saidu Real Estate',
    phone: '+232 77 112 2334',
    email: 'j.saidu@saidure.com',
    address: 'Siaka Stevens Street, Central Freetown',
    notes: 'Regular client for bespoke office furniture and hardwood paneling.',
    registrationDate: '2026-05-28',
  },
  {
    id: 'cust-03',
    name: 'Alusine Mansaray',
    company: 'Sierra Heritage Gallery',
    phone: '+232 30 889 0011',
    email: 'alusine@sierraheritage.org',
    address: 'High Street, Aberdeen, Freetown',
    notes: 'Curates premium hand-carved mahogany panels and cultural status seats.',
    registrationDate: '2026-06-15',
  },
  {
    id: 'cust-04',
    name: 'Dr. Sia Koroma',
    company: 'The Peninsula Lodge',
    phone: '+232 78 998 7766',
    email: 'sia.koroma@peninsulalodge.com',
    address: 'Tokeh Beach Road, Western Area Rural',
    notes: 'Eco-lodge owner ordering durable outdoor teak loungers and structural gazebos.',
    registrationDate: '2026-07-02',
  }
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-01',
    name: 'Alimamy Kamara',
    role: 'Carpenter',
    phone: '+232 76 111 2222',
    email: 'alimamy.kamara@swedsfree.com',
    status: 'Active',
    baseSalary: 5200,
    dailyRate: 190,
    hireDate: '2024-05-12',
    password: '1234',
  },
  {
    id: 'emp-02',
    name: 'Fatmata Fofanah',
    role: 'Carver',
    phone: '+232 76 333 4444',
    email: 'fatmata.fofanah@swedsfree.com',
    status: 'Active',
    baseSalary: 4800,
    dailyRate: 175,
    hireDate: '2025-02-20',
    password: '1234',
  },
  {
    id: 'emp-03',
    name: 'Sahr Tengbeh',
    role: 'Carpenter',
    phone: '+232 77 555 6666',
    email: 'sahr.tengbeh@swedsfree.com',
    status: 'Active',
    baseSalary: 4200,
    dailyRate: 155,
    hireDate: '2025-06-01',
    password: '1234',
  },
  {
    id: 'emp-04',
    name: 'Mariama Jalloh',
    role: 'Designer',
    phone: '+232 30 777 8888',
    email: 'mariama.jalloh@swedsfree.com',
    status: 'Active',
    baseSalary: 6000,
    dailyRate: 200,
    hireDate: '2025-01-15',
    password: '1234',
  },
  {
    id: 'emp-05',
    name: 'Ibrahim Kargbo',
    role: 'Sander',
    phone: '+232 88 999 0000',
    email: 'ibrahim.kargbo@swedsfree.com',
    status: 'Active',
    baseSalary: 3200,
    dailyRate: 110,
    hireDate: '2025-05-20',
    password: '1234',
  },
  {
    id: 'emp-06',
    name: 'Isatu Conteh',
    role: 'Polisher',
    phone: '+232 76 222 3333',
    email: 'isatu.conteh@swedsfree.com',
    status: 'Active',
    baseSalary: 3800,
    dailyRate: 130,
    hireDate: '2025-08-01',
    password: '1234',
  },
  {
    id: 'emp-07',
    name: 'Amadu Sesay',
    role: 'Manager',
    phone: '+232 76 555 5555',
    email: 'amadu.sesay@swedsfree.com',
    status: 'Active',
    baseSalary: 8000,
    dailyRate: 280,
    hireDate: '2023-10-01',
    password: 'manager',
  },
  {
    id: 'emp-08',
    name: 'Emmanuel Cole',
    role: 'Admin',
    phone: '+232 76 666 7777',
    email: 'emmanuel.cole@swedsfree.com',
    status: 'Active',
    baseSalary: 9500,
    dailyRate: 350,
    hireDate: '2022-04-01',
    password: 'admin',
  },
  {
    id: 'emp-09',
    name: 'Kadiatu Bangura',
    role: 'Auditor',
    phone: '+232 77 888 9999',
    email: 'kadiatu.bangura@swedsfree.com',
    status: 'Active',
    baseSalary: 6500,
    dailyRate: 220,
    hireDate: '2025-11-10',
    password: 'audit',
  }
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-01',
    customerId: 'cust-01',
    customerName: 'Aminata Kallon',
    title: 'Victorian Walnut Desk',
    description: 'Custom Victorian style desk with American Walnut, carved details, and high-gloss polish.',
    assignedEmployees: ['emp-01', 'emp-05', 'emp-06'],
    status: 'Ready for Polishing',
    startDate: '2026-07-01',
    dueDate: '2026-07-28',
    quoteAmount: 12500,
    laborCost: 2200,
    otherCosts: 300,
    materialsUsed: [
      { itemId: 'inv-01', name: 'American Walnut (2" x 12")', quantity: 150, unitCost: 16.5, totalCost: 2475 },
      { itemId: 'inv-06', name: 'Gorilla Wood Glue Premium', quantity: 2, unitCost: 22.0, totalCost: 44 }
    ],
    payments: [
      { id: 'pay-01', amount: 6250, date: '2026-07-01', method: 'Bank Transfer' }
    ]
  },
  {
    id: 'job-02',
    customerId: 'cust-03',
    customerName: 'Alusine Mansaray',
    title: 'Live Edge Dining Table',
    description: 'A gorgeous rustic-modern live edge oak dining table with industrial legs.',
    assignedEmployees: ['emp-02', 'emp-03'],
    status: 'In Progress',
    startDate: '2026-07-05',
    dueDate: '2026-08-02',
    quoteAmount: 9800,
    laborCost: 1800,
    otherCosts: 250,
    materialsUsed: [
      { itemId: 'inv-02', name: 'White Oak Planks (1.5" x 8")', quantity: 180, unitCost: 14.8, totalCost: 2664 }
    ],
    payments: [
      { id: 'pay-02', amount: 4900, date: '2026-07-05', method: 'Check' }
    ]
  },
  {
    id: 'job-03',
    customerId: 'cust-02',
    customerName: 'Joseph Saidu',
    title: 'Custom Cabinetry Set',
    description: 'Modern kitchen and storage cabinetry set using hard maple boards and heavy duty slides.',
    assignedEmployees: ['emp-03', 'emp-04'],
    status: 'In Progress',
    startDate: '2026-07-10',
    dueDate: '2026-08-15',
    quoteAmount: 15400,
    laborCost: 2800,
    otherCosts: 400,
    materialsUsed: [
      { itemId: 'inv-03', name: 'Hard Maple Board (1" x 6")', quantity: 120, unitCost: 13.5, totalCost: 1620 },
      { itemId: 'inv-09', name: 'Heavy-Duty Ball Bearing Drawer Slides', quantity: 8, unitCost: 15.0, totalCost: 120 }
    ],
    payments: [
      { id: 'pay-03', amount: 7700, date: '2026-07-10', method: 'Bank Transfer' }
    ]
  },
  {
    id: 'job-04',
    customerId: 'cust-04',
    customerName: 'Dr. Sia Koroma',
    title: 'Modern Coffee Table',
    description: 'Bespoke sleek mid-century modern coffee table using high-end heartwood Teak.',
    assignedEmployees: ['emp-01', 'emp-05'],
    status: 'Delivered',
    startDate: '2026-06-15',
    dueDate: '2026-07-10',
    quoteAmount: 6200,
    laborCost: 1100,
    otherCosts: 150,
    materialsUsed: [
      { itemId: 'inv-04', name: 'Premium Teak Planks', quantity: 60, unitCost: 18.0, totalCost: 1080 }
    ],
    payments: [
      { id: 'pay-04', amount: 6200, date: '2026-06-15', method: 'Cash' }
    ]
  },
  {
    id: 'job-05',
    customerId: 'cust-01',
    customerName: 'Aminata Kallon',
    title: 'Rustic Bench Pair',
    description: 'A pair of beautiful outdoor park benches crafted from weather-treated Reclaimed Pine.',
    assignedEmployees: ['emp-02', 'emp-05'],
    status: 'Ready for Sander',
    startDate: '2026-07-08',
    dueDate: '2026-07-25',
    quoteAmount: 4800,
    laborCost: 900,
    otherCosts: 100,
    materialsUsed: [
      { itemId: 'inv-05', name: 'Reclaimed Pine Wood', quantity: 80, unitCost: 9.5, totalCost: 760 }
    ],
    payments: [
      { id: 'pay-05', amount: 2400, date: '2026-07-08', method: 'Mobile Money' }
    ]
  }
];

export const INITIAL_INVENTORY_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: 'tx-inv-01',
    itemId: 'inv-01',
    itemName: 'American Walnut (2" x 12")',
    type: 'INWARDS',
    quantity: 1000,
    unitCost: 16.5,
    totalValue: 16500,
    date: '2026-06-01',
    purpose: 'Bulk wood supplier purchase',
  },
  {
    id: 'tx-inv-02',
    itemId: 'inv-02',
    itemName: 'White Oak Planks (1.5" x 8")',
    type: 'INWARDS',
    quantity: 800,
    unitCost: 14.8,
    totalValue: 11840,
    date: '2026-06-01',
    purpose: 'Bulk wood supplier purchase',
  },
  {
    id: 'tx-inv-05',
    itemId: 'inv-01',
    itemName: 'American Walnut (2" x 12")',
    type: 'OUTWARDS',
    quantity: 150,
    unitCost: 16.5,
    totalValue: 2475,
    date: '2026-07-01',
    purpose: 'Used in Victorian Walnut Desk',
    referenceId: 'job-01',
  },
  {
    id: 'tx-inv-06',
    itemId: 'inv-02',
    itemName: 'White Oak Planks (1.5" x 8")',
    type: 'OUTWARDS',
    quantity: 180,
    unitCost: 14.8,
    totalValue: 2664,
    date: '2026-07-05',
    purpose: 'Used in Live Edge Dining Table',
    referenceId: 'job-02',
  },
];

export const INITIAL_FINANCIALS: FinancialTransaction[] = [
  {
    id: 'fin-01',
    type: 'EXPENDITURE',
    category: 'Material Purchase',
    amount: 16500,
    date: '2026-06-01',
    description: 'Bulk American Walnut Lumber (1000 Board Feet)',
  },
  {
    id: 'fin-02',
    type: 'EXPENDITURE',
    category: 'Material Purchase',
    amount: 11840,
    date: '2026-06-01',
    description: 'Bulk White Oak Planks (800 Board Feet)',
  },
  {
    id: 'fin-03',
    type: 'INCOME',
    category: 'Job Payment',
    amount: 6250,
    date: '2026-07-01',
    description: '50% Deposit for Victorian Walnut Desk - Ama Serwaa',
    referenceId: 'job-01',
  },
  {
    id: 'fin-04',
    type: 'INCOME',
    category: 'Job Payment',
    amount: 4900,
    date: '2026-07-05',
    description: '50% Deposit for Live Edge Dining Table - Sowah Quarshie',
    referenceId: 'job-02',
  },
  {
    id: 'fin-05',
    type: 'INCOME',
    category: 'Job Payment',
    amount: 7700,
    date: '2026-07-10',
    description: '50% Deposit for Custom Cabinetry Set - John Mensah',
    referenceId: 'job-03',
  },
  {
    id: 'fin-06',
    type: 'INCOME',
    category: 'Job Payment',
    amount: 6200,
    date: '2026-06-15',
    description: '100% Payment for Modern Coffee Table - Dr. Abena Boateng',
    referenceId: 'job-04',
  },
  {
    id: 'fin-07',
    type: 'INCOME',
    category: 'Job Payment',
    amount: 2400,
    date: '2026-07-08',
    description: '50% Deposit for Rustic Bench Pair - Ama Serwaa',
    referenceId: 'job-05',
  },
  {
    id: 'fin-08',
    type: 'EXPENDITURE',
    category: 'Rent',
    amount: 3000,
    date: '2026-07-19',
    description: 'Swedsfree Woodshop monthly rent - July 2026',
  }
];

export const INITIAL_DAILY_WORK_LOGS: DailyWorkLog[] = [
  {
    id: 'log-01',
    employeeId: 'emp-01',
    employeeName: 'Marcus Thorne',
    jobId: 'job-01',
    jobTitle: 'Victorian Walnut Desk',
    date: '2026-07-18',
    timeStarted: '08:00',
    timeEnd: '17:00',
    location: 'Main Woodshop (Bay A)',
    comment: 'Completed the initial sanding on the Victorian Walnut Desk drawer runners. Fitted the brass slide hardware for the middle tier drawer. Tolerances are within 0.5mm, drawers pull smoothly.',
    pictureUrl: 'https://images.unsplash.com/photo-1534081333815-ae5019106622?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'log-02',
    employeeId: 'emp-02',
    employeeName: 'Sarah Jenkins',
    jobId: 'job-02',
    jobTitle: 'Live Edge Dining Table',
    date: '2026-07-19',
    timeStarted: '09:00',
    timeEnd: '16:30',
    location: 'Client Site (East Legon)',
    comment: 'Conducted the first-pass dry assembly of the Live Edge Dining Table. Prepared the custom steel support anchors and leveled the surface to ensure alignment with the rustic stone-paved floor.',
    pictureUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'log-03',
    employeeId: 'emp-03',
    employeeName: 'David O\'Neil',
    jobId: 'job-03',
    jobTitle: 'Custom Cabinetry Set',
    date: '2026-07-19',
    timeStarted: '08:15',
    timeEnd: '17:45',
    location: 'Main Woodshop (Bay B)',
    comment: 'Finished rough cuts for 12 hard maple panels. Set up crosscut sleds for absolute precision. Sanded the edge bands to prepare for jointing tomorrow morning.',
    pictureUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80'
  }
];
